// AUTO-GENERATED by objcjs-types custom generator
import type {
  _NSArray,
  _NSData,
  _NSObject,
  _NSSecureCoding,
} from "objcjs-types/Foundation";

export declare class _ASCPublicKeyCredentialDescriptor extends _NSObject {
  static alloc(): _ASCPublicKeyCredentialDescriptor;
  static new(): _ASCPublicKeyCredentialDescriptor;
  init(): _ASCPublicKeyCredentialDescriptor;

  // Instance methods
  initWithCredentialID$transports$(
    credentialID: _NSData,
    allowedTransports: _NSArray | null
  ): _ASCPublicKeyCredentialDescriptor;

  // Properties
  credentialID(): _NSData;
  transports(): _NSArray | null;
}
export interface _ASCPublicKeyCredentialDescriptor extends _NSSecureCoding {}

// Extra stuff
import { AuthenticationServices } from "objcjs-types/AuthenticationServices";
export const ASCPublicKeyCredentialDescriptor =
  AuthenticationServices.ASCPublicKeyCredentialDescriptor as unknown as typeof _ASCPublicKeyCredentialDescriptor;
