import type { _NSData } from "../foundation/nsdata.js";
import { AuthenticationServices } from "./index.js";
import type { NobjcObject } from "objc-js";

/**
 * ASAuthorizationPublicKeyCredentialPRFRegistrationOutput
 *
 * The output of a PRF (Pseudo-Random Function) extension during registration.
 * https://developer.apple.com/documentation/authenticationservices/asauthorizationpublickeycredentialprfregistrationoutput-swift.struct
 *
 * This class represents the result of a PRF extension operation during a registration ceremony.
 * The PRF extension allows the authenticator to generate deterministic pseudo-random values
 * that can be used for key derivation or other cryptographic purposes.
 */
declare class _ASAuthorizationPublicKeyCredentialPRFRegistrationOutput extends NobjcObject {
  /**
   * The first pseudo-random output value.
   *
   * This is the primary output value generated by the PRF extension during registration.
   * It's derived from the credential's private key and the input values provided during
   * registration.
   *
   * @returns NSData containing the first PRF output value, or nil if not available
   */
  first(): _NSData | null;

  /**
   * The second pseudo-random output value.
   *
   * This is the secondary output value generated by the PRF extension during registration.
   * It's derived from the credential's private key and the second input value provided
   * during registration.
   *
   * @returns NSData containing the second PRF output value, or nil if not available
   */
  second(): _NSData | null;

  /**
   * Indicates whether the PRF extension is supported by the authenticator.
   *
   * @returns true if the PRF extension is supported, false otherwise
   */
  isSupported(): boolean;
}

export const ASAuthorizationPublicKeyCredentialPRFRegistrationOutput =
  AuthenticationServices.ASAuthorizationPublicKeyCredentialPRFRegistrationOutput as unknown as typeof _ASAuthorizationPublicKeyCredentialPRFRegistrationOutput;

export type { _ASAuthorizationPublicKeyCredentialPRFRegistrationOutput };
